import { Decimal } from '@orthofollow/shared'
import type { AnalysisDefinition } from '../types'

export const P01_ANALYSES: AnalysisDefinition[] = [
  {
    id:              'P01.A01',
    protocolId:      'P01',
    displayName:     'Simetria Facial Vertical',
    valueType:       'CLASSIFICATION',
    unit:            'NONE',
    constraint:      {
      minInclusive:  false,
      maxInclusive:  false,
      allowedValues: ['SYMMETRIC', 'ASYMMETRIC_MILD', 'ASYMMETRIC_MODERATE', 'ASYMMETRIC_SEVERE'],
    },
    isRequired:      true,
    formulaInputFor: ['facial-vertical-symmetry'],
  },
  {
    id:              'P01.A02',
    protocolId:      'P01',
    displayName:     'Desvio de Linha Média (mm)',
    valueType:       'SCALAR_MM',
    unit:            'MM',
    constraint:      { minInclusive: true, maxInclusive: true },
    isRequired:      true,
    formulaInputFor: ['midline-deviation'],
  },
  {
    id:              'P01.A03',
    protocolId:      'P01',
    displayName:     'Proporção Terço Superior (%)',
    valueType:       'SCALAR_PERCENT',
    unit:            'PERCENT',
    constraint:      { minInclusive: true, maxInclusive: true },
    isRequired:      true,
    formulaInputFor: ['facial-thirds-upper'],
  },
  {
    id:              'P01.A04',
    protocolId:      'P01',
    displayName:     'Proporção Terço Médio (%)',
    valueType:       'SCALAR_PERCENT',
    unit:            'PERCENT',
    constraint:      { minInclusive: true, maxInclusive: true },
    isRequired:      true,
    formulaInputFor: ['facial-thirds-middle'],
  },
  {
    id:              'P01.A05',
    protocolId:      'P01',
    displayName:     'Proporção Terço Inferior (%)',
    valueType:       'SCALAR_PERCENT',
    unit:            'PERCENT',
    constraint:      { minInclusive: true, maxInclusive: true },
    isRequired:      true,
    formulaInputFor: ['facial-thirds-lower'],
  },
  {
    id:              'P01.A06',
    protocolId:      'P01',
    displayName:     'Perfil Facial',
    valueType:       'CLASSIFICATION',
    unit:            'NONE',
    constraint:      {
      minInclusive:  false,
      maxInclusive:  false,
      allowedValues: ['CONVEX', 'STRAIGHT', 'CONCAVE'],
    },
    isRequired:      true,
    formulaInputFor: ['facial-profile'],
  },
  {
    id:              'P01.A07',
    protocolId:      'P01',
    displayName:     'Ângulo Nasolabial (°)',
    valueType:       'SCALAR_DEGREES',
    unit:            'DEGREES',
    constraint:      { minInclusive: true, maxInclusive: true },
    isRequired:      true,
    formulaInputFor: ['nasolabial-angle'],
  },
  {
    id:              'P01.A08',
    protocolId:      'P01',
    displayName:     'Projeção do Mento',
    valueType:       'CLASSIFICATION',
    unit:            'NONE',
    constraint:      {
      minInclusive:  false,
      maxInclusive:  false,
      allowedValues: ['NORMAL', 'RETRUDED', 'PROTRUDED'],
    },
    isRequired:      true,
    formulaInputFor: ['chin-projection'],
  },
  {
    id:              'P01.A09',
    protocolId:      'P01',
    displayName:     'Simetria Nasal',
    valueType:       'CLASSIFICATION',
    unit:            'NONE',
    constraint:      {
      minInclusive:  false,
      maxInclusive:  false,
      allowedValues: ['NORMAL', 'DEVIATED_LEFT', 'DEVIATED_RIGHT'],
    },
    isRequired:      true,
    formulaInputFor: ['nasal-symmetry'],
  },
  {
    id:              'P01.A10',
    protocolId:      'P01',
    displayName:     'Razão Labial Superior/Inferior',
    valueType:       'SCALAR_RATIO',
    unit:            'RATIO',
    constraint:      { minInclusive: true, maxInclusive: true },
    isRequired:      true,
    formulaInputFor: ['lip-ratio'],
  },
  {
    id:              'P01.A11',
    protocolId:      'P01',
    displayName:     'Competência Labial',
    valueType:       'CLASSIFICATION',
    unit:            'NONE',
    constraint:      {
      minInclusive:  false,
      maxInclusive:  false,
      allowedValues: ['COMPETENT', 'INCOMPETENT', 'POTENTIALLY_INCOMPETENT'],
    },
    isRequired:      true,
    formulaInputFor: ['lip-competence'],
  },
  {
    id:              'P01.A12',
    protocolId:      'P01',
    displayName:     'Exposição Dentária no Sorriso (mm)',
    valueType:       'SCALAR_MM',
    unit:            'MM',
    constraint:      { minInclusive: true, maxInclusive: true },
    isRequired:      true,
    formulaInputFor: ['smile-exposure'],
  },
]
